############################
## CHANGE THESE
############################

baseURL: 'https://Masum-Osman.github.io/masum-osman.github.io'
title: masum-osman.github.io

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


