############################
## CHANGE THESE
############################

baseURL: 'https://masum-osman.github.io'
title: Masum Osman

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


