############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: About
  url: /about/
  weight: 20
- name: Work Experience
  url: /experience/
  weight: 30
- name: Services
  url: /services/
  weight: 50
- name: Skills
  url: /skills/
  weight: 80
- name: Blogs
  url: /blogs/
  weight: 100


# - name: Licenses & certifications
#   url: /certifications/
#   weight: 60
# - name: Projects
#   url: /projects/
#   weight: 70
# - name: Recommendations
#   url: /recommendations/
#   weight: 90
# - name: Education
#   url: /education/
#   weight: 40