############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: About
  url: /about/
  weight: 20
- name: Work Experience
  url: /experience/
  weight: 30
- name: Education
  url: /education/
  weight: 50
- name: Skills
  url: /skills/
  weight: 80
- name: Blogs
  url: /blog/
  weight: 100